version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - ./:/var/lib/drone/
    restart: always
    environment:
      - DRONE_HOST=https://3d435577.ngrok.io
      - DRONE_OPEN=true
      - DRONE_SECRET=drone-workshop
      - DRONE_ADMIN=e61983

      # GitHub Config
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=64e4076391ee01180c2b
      - DRONE_GITHUB_SECRET=f021d3deb90703d4984b7ad689ba0781bf5c4b5f

  drone-agent:
    image: drone/agent:0.8
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=drone-workshop
      - DRONE_MAX_PROCS=3
